aws_vpc_id = "vpc-935824e9"
aws_secrets_name = "7Soat"

rds_database_security_group_name= "tech-challenge-7soat-db-sg"
rds_database_security_group_description = "Security group for 7 soat tech challenge database"
rds_database_security_group_ingress_eks_sgids = ["sg-0f9a8f1622c0e55aa","sg-0b60838921e123654"]
rds_subnet_group_name = "tech_challenge_7soat_subnet_group_db"
rds_subnet_group_subnetIDs = ["subnet-0628055b427ab2fe6", "subnet-0d501603dbb6981a0"]
rds_database_primary = "tech-challenge-7soat-db-primary"
rds_database_engine = "postgres"
rds_database_engine_version = "16.4"
rds_database_instance_class = "db.t3.small"
rds_database_allocated_storage = 20
rds_database_storage_type = "gp2"
rds_database_multi_az = false
rds_database_skip_final_snapshot = true
rds_database_publicly_accessible = true
rds_database_backup_retention_period = 7
rds_database_apply_immediately = true
rds_database_name = "tech_challenge_7soat_db"
rds_database_replica = "tech-challenge-7soat-db-replica"

orders_dynamodb_table_name         = "orders"
orders_dynamodb_table_billing_mode = "PAY_PER_REQUEST"
orders_dynamodb_table_hash_key     = "id"
orders_dynamodb_table_deletion_protection_enabled = true

products_catalog_database_security_group_name = "tech-challenge-7soat-products-catalog-db-sg"
products_catalog_database_security_group_description = "Security group for 7 soat tech challenge products catalog database"
products_catalog_database_name = "products_catalog_db"
products_catalog_database_engine = "postgres"
products_catalog_database_engine_version = "16.4"
products_catalog_database_instance_class = "db.t3.micro"
products_catalog_database_allocated_storage = 10
products_catalog_database_storage_type = "gp2"
products_catalog_subnet_group_name = "tech_challenge_7soat_products_catalog_subnet_group_db"
products_catalog_subnet_group_subnetIDs = ["subnet-021aa64c7b62eb8f4", "subnet-07075f15ad2baa741"]
products_catalog_database_primary = "tech-challenge-7soat-products-catalog-db-primary"
products_catalog_database_multi_az = false
products_catalog_database_skip_final_snapshot = true
products_catalog_database_publicly_accessible = false
products_catalog_database_backup_retention_period = 7
products_catalog_database_apply_immediately = true
# products_catalog_database_security_group_ingress_eks_sgids = var.products_catalog_database_security_group_ingress_eks_sgids

payments_database_security_group_name = "tech-challenge-7soat-payments-db-sg"
payments_database_security_group_description = "Security group for 7 soat tech challenge payments database"
payments_database_name = "payments_db"
payments_database_engine = "postgres"
payments_database_engine_version = "16.4"
payments_database_instance_class = "db.t3.micro"
payments_database_allocated_storage = 10
payments_database_storage_type = "gp2"
payments_subnet_group_name = "tech_challenge_7soat_payments_subnet_group_db"
payments_subnet_group_subnetIDs = ["subnet-021aa64c7b62eb8f4", "subnet-07075f15ad2baa741"]
payments_database_primary = "tech-challenge-7soat-payments-db-primary"
payments_database_multi_az = false
payments_database_skip_final_snapshot = true
payments_database_publicly_accessible = false
payments_database_backup_retention_period = 7
payments_database_apply_immediately = true
# payments_database_security_group_ingress_eks_sgids = var.payments_database_security_group_ingress_eks_sgids