name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    #environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_RDS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_RDS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_RDS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -var-file="values.tfvars"

      - name: Production approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers:  thiagothalison1,rafaelsmonte,vitors95
          minimum-approvals: 1
          issue-title: "Deploying DB to prod"
          issue-body: "Please approve or deny the deployment of DB to prod"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
        

      - name: Apply Terraform
        run: terraform apply -var-file="values.tfvars" -auto-approve
        working-directory: .