name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    #environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_RDS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_RDS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_RDS_REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan -var-file="values.tfvars"

      - name: Request approval to Apply Terraform
        if: ${{ github.event_name == 'push' }}
        uses: peter-evans/approve-pull-request-action@v3
        with:
          approvers: 'thiagothalison1 ,vitors95 , rafaelsmonte' 
          message: 'Please approve to apply Terraform changes.'
          
      - name: Apply Terraform
        if: ${{ github.event_name == 'push' && steps.request-approval.outcome == 'success' }}
        run: terraform apply -var-file="values.tfvars" -auto-approve
        working-directory: .